'use strict';

export const ES_CONNECT = 'ES_CONNECT';
export const SWITCH_MAIN_CONTENT = 'SWITCH_MAIN_CONTENT';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
